---
title: "Data Cleaning and Analysis"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
    includes:
      in_header: header.html
  word_document: default
  pdf_document:
    highlight: zenburn
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
print(getwd())
library(car)
library(dplyr)
library(carData)
library(ggplot2)
```


### Asignatura:

Tipología y Ciclo de vida de los datos

### Autores:


José Ramón Martínez-Carbonell Martín

Miguel Ángel Pérez García


# Exploración

```{r}
#Captura
cites <- read.csv("cites_2021_original.csv", header = TRUE)
head(cites)
summary(cites)
```

```{r}
#Detección de nulos/vacíos
#sapply(cites, function(x) sum(is.na(x))) # NA
sapply(cites, function(x) sum(x=="")) #Si es vacio
#sapply(cites, function(x) sum(x==" ")) # Si no es vacio, aunque tiene un espacio
```

# Limpieza

```{r}
#Declaramos los nuevas columnas que utilizaremos
auxNumber <- c()
auxType <- c()
#Según el si el campo de importación/exportación está vacío o no,
#vamos creando el vector según convenga
for (i in 1:nrow(cites)) {
  if(!is.na(cites$Importer.reported.quantity[i])){
    auxNumber[i] <- cites$Importer.reported.quantity[i]
    auxType[i] <- "Imported"
  }else if(!is.na(cites$Exporter.reported.quantity[i])){
    auxNumber[i] <- cites$Exporter.reported.quantity[i]
    auxType[i] <- "Exported"
  }
}
#Asignamos las nuevas columnas al dataset
cites$Exportation.type <- auxType
cites$Exportation.number <- auxNumber
```


```{r}
#Creación de boxplot para detección de outliers
boxplot(cites$Exportation.number)
boxplot.stats(cites$Exportation.number)$out
```


```{r}
#Duplicados
cites[duplicated(cites),]
dim(cites)
```



```{r}
#Eliminar duplicados
cites = unique(cites)
dim(cites)
```

```{r}
#Eliminamos las columnas que ya no nos interesan
cites$Origin <- NULL
cites$Importer.reported.quantity <- NULL
cites$Exporter.reported.quantity <- NULL
cites$Family <- NULL
cites$Order <- NULL
cites$Genus <- NULL
```



```{r}
#Añadir nivel Not applied a Unit, Class, Source and Genus
levels(cites$Unit) <- c(levels(cites$Unit), "Not applied")
levels(cites$Class) <- c(levels(cites$Class), "Not applied")
levels(cites$Source) <- c(levels(cites$Source), "Not applied")
levels(cites$Purpose) <- c(levels(cites$Purpose), "Not applied")

```


```{r}
#sustición de cadena vacía por "Not applied"
for (i in 1:nrow(cites)) {
  for(j in 1:ncol(cites)){
    if((cites[i,j]=="")){
      cites[i,j] <- "Not applied"
    }
  }
}
```

```{r}
#Guardamos el dataset transformado
write.csv(cites, "cites_2021_limpio.csv")
```

# Análisis

```{r}
#Prueba de shapiro-wilk
shapiro.test(cites$Exportation.number)
```

```{r}
install.packages("car")
```

```{r}
leveneTest(y = cites$Exportation.number, group = cites$Importer, center = "median")
```
```{r}
leveneTest(y = cites$Exportation.number, group = cites$Exportation.type, center = "median")
```

```{r}
table1 <- table(cites$Importer, cites$Taxon)
chisq.test(table1)
```

```{r}
table2 <- table(cites$Exporter, cites$Taxon)
chisq.test(table2)
```

```{r}
table2 <- table(cites$Exporter, cites$Exportation.number)
chisq.test(table2)
```


```{r}
table2 <- table(cites$Importer, cites$Exportation.number)
chisq.test(table2)
```
```{r}
model <- lm(cites$Exportation.number ~ cites$Exportation.type)
summary(model)
```


```{r}
model <- lm(cites$Exportation.number ~ cites$Term)
summary(model)
```

```{r}
model <- lm(cites$Exportation.number ~ cites$Term + cites$Purpose)
anova(model)
```

# Visualización

```{r}
#Clases intercambio
ggplot(data=cites,aes(x=Class, fill=Exportation.type)) + geom_bar() + xlab("Animales por clase") + labs(fill = "Exportation.type") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#Cantidad de intercambios de exportación por paises
ggplot(data=subset(cites, Exportation.type == "Exported"),aes(x=Exporter, fill=Exporter)) + geom_bar() + xlab("Paises Exportadores") +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none")

#Cantidad de intercambios de importación por paises
ggplot(data=subset(cites, Exportation.type == "Imported"),aes(x=Importer, fill=Importer)) + geom_bar() + xlab("Paises Importadores") +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none")

#Paises/importaciones_de_piel
ggplot(data=subset(cites, Term == "skins" | Term == "skin pieces"),aes(x=Importer, fill=Importer)) + geom_bar() + xlab("Paises Importadores de piel")


tempA <- subset(cites, App. == "III")
tempB <- select(tempA,Taxon,Exportation.number)

animals_count = aggregate(x = tempB$Exportation.number,                
          by = list(Taxon = tempB$Taxon),             
          FUN = sum)


#Animales protegidos
ggplot(data=animals_count, aes(x=Taxon, y=x, fill=Taxon, label=x)) + geom_bar(stat='identity') + xlab("Animales protegidos") + labs(fill = "Taxon") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + geom_text(aes(label = x), position = position_stack(0.5), size=3)

```